### ISSUE TITLE
[Tournoi] Notification manquante 

### ISSUE THREAD

**Issue by Poonex32** [leek-wars/leek-wars#190]
Lorsque deux compositions dans lesquelles nous sommes présent s'affrontent, une seule notification est générée, laissant croire à un match nul ou une défaite à la manche précédente.

![](http://image.prntscr.com/image/ddd3638f95954b0b9ab53b0688298e11.png)

![](http://image.prntscr.com/image/e4912957ff154b9b8f0bd3f01e2b7d74.png)

**Comment by 5pilow** [comment]
Le bug sera corrigé dans la màj 2.15, merci !
