### ISSUE TITLE
Idée de features pour la web app

### ISSUE THREAD

**Issue by Becold** [leek-wars/leek-wars#295]
* ~Meilleur cache (?). Peut-être profiter du SW.~
* ~[Ok] Dans un topic, impossible d'appuyer sur le bouton recherche (en haut à droite).~
* ~[Ok] Dans le potager, en haut à droite, nb de combats restants ou timer.~
* ~Update plus lent sur les statistiques.~
* ~Gestures pour ouvrir/fermer le menu (HammerJS ?).~
* ~Refaire l'historique.~
* ~[Ok] En ouvrant la liste des mp, assombrir le reste de l'écran (comme le menu).~
* ~[Ok] Désactiver le scroll en ayant le menu ou le panel des mp/notifs ouverts.~

* Rotation du canvas de jeu en fullscreen. (le haut du player est coupé, il manque la barre de vies générale)
* Sur un topic, bouton pour revenir dans la catégorie.
* Mettre un séparateur en dessous des poireaux et le reste du menu
* Ajouter le nombre de points de talent du farmer à côté de son nom dans le menu

**Comment by Becold** [comment]
* Mettre un séparateur en dessous des poireaux et le reste du menu
* Ajouter le nombre de points de talent du farmer à côté de son nom dans le menu

**Comment by Becold** [comment]
J'ai mis à jour cette issue

**Comment by 5pilow** [comment]
La plupart sont fait maintenant, je ferme :)
