### ISSUE TITLE
[Chat] Better mute

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars#303]
Je pense qu'il faudrait séparer la notion de "censure" et de "mute".

Actuellement, on peux mute quelqu'un, ce qui censure tout ses messages visibles sur le chat.
Problème, les messages restent visibles pour quelqu'un qui arriverait après le mute, ou qui simplement rafraîchit sa page.
Du coup, si quelqu'un poste des propos haineux, des liens gênants, etc. On ne peut pas les supprimer/censurer définitivement.
De même, on peut avoir besoin de mute quelqu'un sans forcément censurer tout ses messages. Ou au contraire, censure un message sans forcément le mute.

La liste des mutes, déjà dit, mais comme ça c'est écrit :D
La possibilité de mute pour une certaine durée, ça pourrait être utile aussi.

**Comment by 5pilow** [comment]
Entièrement d'accord avec tout ça !

**Comment by 5pilow** [comment]
C'est fait !
