### ISSUE TITLE
[leek] Improve stat distribution popup

### ISSUE THREAD

**Issue by Shakadak** [leek-wars/leek-wars#316]
I'm gathering here the suggestions that appeared in discussions regarding the improvement of the capital's distribution's popup:

- [ ] Add a button that pre-invest as much capital as possible in a specific stat.

- [ ] Add a button that reset the capital currently pre-invested in a specific stat.

**Comment by 5pilow** [comment]
J'ai rajouté le bouton pour retirer le capital ;)
