### ISSUE TITLE
[Compatibilité Edge] [Editeur] Première lettre d'une IA non modifiable

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars#322]
Lorsque l'on tente de renommer une IA dans l'éditeur, avec le navigateur Edge, on ne peut pas supprimer la première lettre du nom.

[https://leekwars.com/forum/category-3/topic-8863/page-1#57309](url)

**Comment by 5pilow** [comment]
Je pense que c'est bon maintenant :)
