### ISSUE TITLE
[Chat] Smiley " :B " en format twemoji

### ISSUE THREAD

**Issue by GuimDev** [leek-wars/leek-wars#338]
Salut,

je souhaite rajouter le Smiley " :B " en format twemoji : ":grimaceB:"

Le voici en .svg :
http://svgur.com/s/6bn

Le voici en .png :
https://i.imgur.com/Lqusf9l.png
https://i.imgur.com/CCkGB2d.png

Le voici en .svg :
![](http://svgur.com/i/6bn.svg)

Le voici en .png :
![](https://i.imgur.com/Lqusf9l.png)
![](https://i.imgur.com/CCkGB2d.png)

**Comment by GuimDev** [comment]
Version peach : (imaginé par : fabInDaGarden )

SVG : http://svgur.com/s/6t9

![302222](https://user-images.githubusercontent.com/16418215/40850073-f2784032-65c3-11e8-9bcd-b0c37423b2ea.png)
![8jr7yyl](https://user-images.githubusercontent.com/16418215/40850162-2edbc3aa-65c4-11e8-8a67-6a055ff090c4.png)

**Comment by 5pilow** [comment]
Ils arrivent dans la prochaine màj, merci :)
