### ISSUE TITLE
[Editeur] Ajouter un message : "L'éditeur est ouvert dans un autre onglet"

### ISSUE THREAD

**Issue by GuimDev** [leek-wars/leek-wars#341]
Bonjour,

Je propose d'ajouter un système qui ajoute un bandeau en haut de la page (un peu comme le bandeau des cookies sur les sites commerciaux).

"L'éditeur est ouvert dans un autre onglet"

Puis-je mettre en place un tel système ? (J'utiliserai sessionStorage pour faire ça).

**Comment by 5pilow** [comment]
Done
