### ISSUE TITLE
[Amélioration] Actualisation des informations d'un onglet à l'autre

### ISSUE THREAD

**Issue by GuimDev** [leek-wars/leek-wars#342]
Bonjour,

Certaine fois les données tels que les hubs, nombres de combats... Ne sont pas à jour. Je propose de faire un système avec sessionStorage/localStorage et un setInterval qui actualiserait les informations.

NB : Je crée plein d'issue car si j'ai le temps (un après-midi) je ferais une flopée de PR. ;)

**Comment by Naheulf** [comment]
Je ne suis pas sûr que l'utilisation de sessionStorage corrige réellement le problème. D'après la doc https://developer.mozilla.org/fr/docs/Web/API/Window/sessionStorage :  
> En revanche, une session de navigation n'est valable que pour le contexte de navigation actuel, c'est-à-dire que le fait d'ouvrir une page dans un nouvel onglet ou dans une nouvelle fenêtre provoquera l'initialisation d'une nouvelle session de navigation, ce qui diffère du comportement des sessions utilisant des cookies
Si j'ai bien compris on ne peut malheureusement pas synchroniser les onglets avec ça...

**Comment by PerthuisQuentin** [comment]
Un recodage du client avec Redux alors ? :B

**Comment by GuimDev** [comment]
@Naheuf Ce que dit le texte, n'est pas ce que tu as compris.

Lis les phrases depuis le début :

 - L'objet global sessionStorage est similaire à Window.localStorage, à la différence que les données enregistrées dans sessionStorage ont une durée vie limitée et expirent à la fin de la session de navigation actuelle. Une session de navigation dure aussi longtemps que le navigateur est ouvert et s'étend sur plusieurs chargements, rechargements et restaurations de pages.

**Comment by GuimDev** [comment]
De plus au pire il y a localStorage.

**Comment by 5pilow** [comment]
Beaucoup d'informations sont maintenant synchronisées sur tous les onglets via WS : talent, habs, notifs, chats
