### ISSUE TITLE
Completion automatique des pseudos dans les chats

### ISSUE THREAD

**Issue by 5pilow** [leek-wars/leek-wars#38]

**Comment by jonathanjdev** [comment]
Je ne sais pas si tu as re-réfléchi à la question
Est-ce que l'on prend seulement le nom des joueurs qui ont déjà écrit dans le tchat (ce qui permet de limiter le nombre de personnes) ou veux-tu vraiment prendre en auto complétion la liste de tous les joueurs inscrits ? (je trouve que ce n'est pas du tout une bonne idée)

**Comment by 5pilow** [comment]
Oui je compte avoir la complétion de tous les pseudos du jeu, pour plusieurs raisons :
- Si tu as envie de citer un joueur qui parlait avant mais qui vient de se déco
- Si tu veux citer un joueur en général d'ailleurs, même si il est pas connecté depuis longtemps
- Le chargement peut se faire en deux temps pour éviter un souci de rapidité, d'abord on utilise la liste des joueurs connectés, puis on recherche en base (ce qui n'est pas bien long non plus)

**Comment by Becold** [comment]
Une idée pour alléger le coup en charge du serveur pour cet feature serait de : 
- Mettre en place une instance Redis qui stockerait tous les pseudos (+ de rapidité vu que c'est nosql)
- Chercher en mémoire local (les personnes connectées) si le mot commence par @ 
- Faire la requete ajax seulement lorsque le pseudo/mot commence par un @ et fait plus de 3-4 lettres et seulement si l'utilisateur n'a pas tappé depuis 400ms

**Comment by Becold** [comment]
Ce userscript est déjà une bonne base : https://github.com/jogalaxy/leekwars_v2/raw/master/leekwars_tchat_pseudo_autocomplete.user.js
Il suffirait qu'il soit basé sur les gens connectés + les gens en messages privés (+ les gens dans le chat) et ce serait nickel pour la partie "offline"
