### ISSUE TITLE
Notification quand quelqu'un mentionne notre pseudo

### ISSUE THREAD

**Issue by 5pilow** [leek-wars/leek-wars#39]

**Comment by jonathanjdev** [comment]
Tu veux que ce soit seulement le pseudo exacte ou est-ce qu'on pourrait rajouter des surnoms dans les paramètres du jeu ?

**Comment by 5pilow** [comment]
J'ai pas prévu de rajouter des surnoms non, mais peut être qu'après on pourrait faire un système d'alerte plus général.

Pour la citation c'est uniquement quand on écrit le pseudo du joueur exactement, et précédé d'un @, comme sur twitter ou autre, par exemple @jojo123 etc. et je comptais avoir cette référence en bleu et qui redirige vers la page du joueur en question.
