### ISSUE TITLE
Plus de place pour les Logs 

### ISSUE THREAD

**Issue by Arthurin** [leek-wars/leek-wars#434]
![18-11-10 at 09 37](https://user-images.githubusercontent.com/6535135/48299325-35179780-e4cc-11e8-954c-b83e98d30064.PNG)
Quand je regarde un combat lire mes logs est la chose la plus importante, pourtant la colonne est tellement dur à lire. Sans le survol de la souris on lit à peine 3 mots avant que le message soit tronqué (et on a rien du tout lorsque les pseudos sont trop long XD) ! Comme on peut le voir sur le screenshot c'est pourtant pas la place qui manque dans la fenêtre !

-> On pourrait gagner pas mal de place en virant le [PseudoPoireau] avant chaque log. Le premier est utile mais vu qu'on joue en tour par tour les suivants sont juste redondant.
-> En sortant ce composant de la zone de combat et en utilisant un style responsive on pourrait avoir droit à ça : 
![leekwars](https://user-images.githubusercontent.com/6535135/48299584-30a0ae00-e4cf-11e8-904c-46c89a913c5c.jpg)

**Comment by 5pilow** [comment]
C'est maintenant implémenté :)
