### ISSUE TITLE
[bug] Certains logs ne s'affichent pas

### ISSUE THREAD

**Issue by Arthurin** [leek-wars/leek-wars#435]
Ils ne s'affichent pas pendant le combat mais sont bien là dans le rapport du combat. Dur à montrer ici mais j'imagine que c'est pareil partout, si tu peux lancer un combat en affichant mes logs voici un combat d'exemple : https://leekwars.com/fight/27083207

**Comment by PerthuisQuentin** [comment]
J'ai lancé un combat au potager, et je n'ai eu des logs qu'au premier tour.
Par contre, après, j'ai lancé pleins de combats, au potager et en test, et j'ai pas réussis à reproduire.

J'ai trouvé un moyen de reproduire finalement.
Si je F5, puis lance des combats au potager, le premier combat n'a de logs qu'au premier tour.

**Comment by yaelMagnier** [comment]
A ce que j'ai vu, le bug arrive si le debug est dans une ia inclue dans le code a l'interieur du corps de la fonction. CAD que l'on a `<code> include("ai avec debug");`

**Comment by BhasherBEL** [comment]
J'ai également eu ce bug, et dans mon IA principale. La structure était comme suit:

`include('mon_IA') ;
mon_IA_fonction(...) ;
debug("ne s'affiche pas") ;
`

**Comment by 5pilow** [comment]
Le bug est corrigé enfin !
