### ISSUE TITLE
[Editeur] [Map custom] Superposition d'objets

### ISSUE THREAD

**Issue by bibimission** [leek-wars/leek-wars#514]
Lorsqu'on édite une map custom, on a la possibilité de créer un point de départ et obstacle à la fois. On fait d'abord clic-droit puis clic-gauche. (Spawn d'abord, obstacle ensuite).
Ce que ça donne c'est un poireau qui apparaît dans un mur :
https://leekwars.com/fight/29590887

Ensuite, il est possible de superposer des poireaux en combat de test sur une map personnalisée, comme l'a relevé BougeLeGrosOrteil dans ce topic :
https://leekwars.com/forum/category-3/topic-9505

**Comment by 5pilow** [comment]
Ce bug est maintenant corrigé !
