### ISSUE TITLE
Variables proposée par l'autocompletion dans le scope d'une fonction

### ISSUE THREAD

**Issue by Neospiro** [leek-wars/leek-wars#524]
Bonjour,

Lorsque je suis dans le scope d'une fonction, l'auto-completion me propose la variable "this" :
![image](https://user-images.githubusercontent.com/4870502/71080735-0ae3df00-218e-11ea-9198-3ff500cf3e5c.png)

Or cette variable n'est pas déclarée : 
![image](https://user-images.githubusercontent.com/4870502/71080789-23ec9000-218e-11ea-9fcf-8c67449ad7b6.png)

EDIT : Pareil pour la variable "arguments"

**Comment by 5pilow** [comment]
this et arguments ont été enlevés des completions, merci !
