### ISSUE TITLE
[Chat] Liens suivis d'un émoticone

### ISSUE THREAD

**Issue by Surkal** [leek-wars/leek-wars#536]
Dans le tchat lorsqu'on insère un lien suivi d'un émoticone (pourtant séparés d'un espace), le code html de l'émoticone s'insère dans l'attribut `href`.

![lien et emoji](https://user-images.githubusercontent.com/18416149/75265061-40d5bd00-57e8-11ea-89a4-936af691fea8.png)

**Comment by 5pilow** [comment]
C'est corrigé !
