### ISSUE TITLE
[LeekScript] arrayFilter ne réordonne pas

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars#541]
Copier coller d'un MP :

J'crois que y'a un truc chelou avec arrayFilter
il supprime les clés, du coup le tableau "devient" associatif
et on peut plus le parcourir avec un for(var i = 0; i < count(array); i++)
(mais avec un for in, oui)

**Comment by 5pilow** [comment]
Done, dans le LeekScript 1.1 :)
