### ISSUE TITLE
[Chat] Mini-doc pour les commandes

### ISSUE THREAD

**Issue by Bulbille** [leek-wars/leek-wars#542]
À côté de la liste des émoticônes (ou dans un onglet de ceux-ci), mettre les commandes doc/fliptable/lenny/latex/code

**Comment by 5pilow** [comment]
Tu penses que Ctrl + Espace après un "/" n'est pas suffisant ?

**Comment by Bulbille** [comment]
Je viens de tenter. Sur une page fraîche, / met directement la liste.
Dès que je referme la liste, plus moyen de la rouvrir, même avec Ctrl+Espace. 
De plus, j'étais pas au courant de la commande :D Elle est écrite quelque part ?
