### ISSUE TITLE
[leek] Tooltip de puce trop haute pour l'écran

### ISSUE THREAD

**Issue by ebatsin** [leek-wars/leek-wars#553]
Sur la vue des poireaux, lorsqu'on édite les puces du poireau, si la tooltip est trop haute, elle empêche de cliquer sur la puce (la tooltip se place devant l'icone de puce).

Ca me le fait sur toutes les puces de bulble.

Navigateur: Firefox (j'utilise le site à 120% de zoom).

![tooltip](https://user-images.githubusercontent.com/9489603/80872386-e0646f80-8cb1-11ea-8c5e-abda579597f9.gif)

**Comment by 5pilow** [comment]
C'est corrigé j'ai laissé un petit décalage pour pouvoir quand même cliquer (plus dur de faire mieux)
