### ISSUE TITLE
Site inutilisable sur safari

### ISSUE THREAD

**Issue by Myystigri** [leek-wars/leek-wars#557]
Hello, je suis sur macOS Big Sur et le site semble inutilisable.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/16547785/93711040-2b8cfb00-fb4b-11ea-8779-46e2732ac074.png">
le contenu de la page ne charge pas, cliquer sur un lien fait apparaître l'erreur visible dans la console, même en accédant manuellement à la page de connexion, le résultat est le même.

**Comment by 5pilow** [comment]
Merci pour le signalement, c'est corrigé normalement !
