### ISSUE TITLE
Game not loading

### ISSUE THREAD

**Issue by magic-space** [leek-wars/leek-wars#563]
After install and start the game is not loading.

`INFO  Starting development server...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
95% emitting CopyPlugin⚠ ｢copy-webpack-plugin｣: unable to locate 'src/wiki/image/' at '/www/public/leek-wars/src/wiki/image'
98% after emitting SizeLimitsPlugin

 WARNING  Compiled with 1 warnings               11:47:04 PM
 warning

unable to locate 'src/wiki/image/' at '/www/public/leek-wars/src/wiki/image'

No type errors found
No lint errors found
Version: typescript 3.9.7, tslint 5.20.1
Time: 30127ms

  App running at:
  - Local:   http://localhost:8080/
  - Network: unavailable

  Note that the development build is not optimized.
  To create a production build, run npm run build.`

I can't open the site.

**Comment by 5pilow** [comment]
Hello, you also have to clone the submodule "wiki", with something like `git submodule update --init --recursive`. Sorry the documentation does not explain this part.

**Comment by magic-space** [comment]
Oh okay my port is in use by nginx how to setup nginx?
Thanks for your answer.

**Comment by 5pilow** [comment]
You can add `devServer: { port: 9999 },` in `module.exports` object, in `vue.config.file` to change the port.

**Comment by 5pilow** [comment]
I fixed the problem with the wiki you had in the first place.
