### ISSUE TITLE
Éditeur se trompe de fichier

### ISSUE THREAD

**Issue by Bulbille** [leek-wars/leek-wars#571]
Erreur 2 : L'éditeur pense que mon fichier est dans le mauvais dossier et donne une erreur pour le mauvais fichier.

Erreur 1 : l'erreur n'existe tout simplement pas dans le fichier cells. Le compilateur est content avec ce fichier. Problème de cache ?

https://i.imgur.com/7gWgXU1.png

**Comment by Bulbille** [comment]
Après plusieurs test, il semblerait que ce soit bien un problème de cache.
Même en f5 la page éditeur, ça compile parfait mais c'est marqué comme "erreur"

**Comment by 5pilow** [comment]
ça devrait être corrigé !
