### ISSUE TITLE
[Combat] Ouvrir les outils de développement ne redimensionne pas le canvas

### ISSUE THREAD

**Issue by ebatsin** [leek-wars/leek-wars#575]
Sur Firefox, l'ouverture de la fenêtre des outils de développement (lorsqu'elle est attachée en bas) perturbe le redimensionnement du canvas de combat.

Pour reproduire:

1. Lancer un combat
2. Ouvrir les outils de dev (F12) (rien ne change, pas de redimensionnement)
3. Fermer les outils de dev (F12 de nouveau) => le canvas devient tout petit et prend la taille qu'il aurait du avoir avec les outils de dev ouverts
4. A partir de maintenant, à chaque ouverture/fermeture des outils de dev, le canvas sera grand quand il devrait être petit et inversement.

https://user-images.githubusercontent.com/9489603/104634975-9be2fd80-56a1-11eb-86fb-6cd9ba60d3e0.mp4

**Comment by 5pilow** [comment]
Merci c'est en prod
