### ISSUE TITLE
[Chat] Autocomplétion bloquée

### ISSUE THREAD

**Issue by PerthuisQuentin** [leek-wars/leek-wars#577]
L'autocomplétion semble se bloquée en tapant "/doc:c"

J'ai vu ça en essayant d'avoir le lien vers CELL_EMPTY.

J'ai essayé tout l'alphabet en première lettre, ça ne le fait qu'avec le "c".

Bizarre bizarre :D

**Comment by 5pilow** [comment]
Je ne reproduit plus, je ferme :)
