### ISSUE TITLE
[LS] AREA_CIRCLE_1 == AREA_PLUS_1

### ISSUE THREAD

**Issue by Bulbille** [leek-wars/leek-wars#579]
Ça pose des soucis lors du débogage de code.
Dans mon cas, j'ai eu 
`global _AoECalc = [
	AREA_POINT 		: [0 : 1]
	AREA_CIRCLE_1 	: [-1 : 3, 0 : 1, 1 : 3],
	AREA_CIRCLE_2 	: [-2 : 4, -1 : 14, 0 : 31, 1 : 14, 2 : 4],
	AREA_CIRCLE_3 	: [-3 : 8, -2 : 28, -1 : 62, 0 : 127, 1: 62, 2 : 28, 3 : 8]
	//AREA_PLUS_1 	: [-1 : 2, 0 : 7, 1 : 2],
	AREA_PLUS_2 	: [-2 : 4, -1 : 4, 0 : 15, 1 : 4, 2 : 4],
	AREA_PLUS_3 	: [-3 : 8, -2 : 8, -1 : 8, 0 : 125, 1 : 8, 2 : 8, 3 : 8],
	AREA_X_1 		: [-1 : 5, 0 : 2, 1 : 5],
	AREA_X_2 		: [-2 : 17, -1 : 10, 0 : 4 , 1 : 10, 2 : 17],
	AREA_X_3 		: [-3 : 65, -2 : 34, -1 : 20, 0 : 8, 1 : 20, 2 : 34, 3 : 65],
	AREA_SQUARE_1 	: [-1 : 7, 0 : 7, 1 : 7],
	AREA_SQUARE_2 	: [-2 : 31, -1 : 31, 0 : 31, 1 : 31, 2 : 31],
	AREA_LASER_LINE : [0 : 1],
	AREA_FIRST_INLINE : [0 : 1] ];`
J'ai prérempli le tableau avec les valeurs que je pensais les bonnes.
Je ne comprenais pas pourquoi en débugguant CIRCLE_1 rien ne changeait. Tout simplement car PLUS_1 écrasait les modifications de CIRCLE_1.
Ce comportement n'est pas intuitif pour deux constantes ayant des noms différents, on s'attend à deux valeurs différentes, même si dans la pratique elles ont le même effet.

Le cas est différent avec BUFF-STRENTGH ET BUFF_FORCE car l'une est dépréciée, c'est juste un changement de nom.
Dans le cas de circle1/plus1, ce sont théoriquement deux choses différentes.
Je propose l'un ou l'autre :
- supprimer PLUS_1
- modifier la valeur de PLUS_1

**Comment by Nyaleph** [comment]
Il me semble que les deux AREA correspondent a la meme taille et que le fait qu'il y existe AREA_CIRCLE_1 et AREA_PLUS_1 est juste pour la completion. Techniquement les deux globales correspondent a la meme figure, donc c'est nomal que les deux aient la meme valeur.
Si elles avaient des valeures différentes, cela pourrait poser des problèmes pour certaines IAs

**Comment by 5pilow** [comment]
La correction que je pense faire est d'ajouter un warning à la création d'un tableau contenant deux fois la même clé :) Mais les constantes de zone me paraissent correctes comme ça, il s'agit d'un synonyme :)
