### ISSUE TITLE
[Doc] getCell(s)ToUseXXOnCell

### ISSUE THREAD

**Issue by Bulbille** [leek-wars/leek-wars#582]
Pour les entrées de la doc de : 
- getCellsToUseWeapon
- getCellsToUseWeaponOnCell
- getCellsToUseWeaponOnCell ignore
- getCellsToUseWeapon
- getCellsToUseWeapon ignore
- getCellsToUseChipOnCell
- getCellsToUseChipOnCellignore

`entity : doc.func_getCellsToUseWeapon_arg_2

ignoredCells : doc.func_getCellsToUseWeapon_arg_3`

**Comment by 5pilow** [comment]
C'est corrigé merci, beaucoup de fonctions étaient touchées !
