### ISSUE TITLE
Unable to change account's email

### ISSUE THREAD

**Issue by glamax13** [leek-wars/leek-wars#585]
Expected results:
- I can change my email by visiting my profile page.

Current result: 
- by visiting "https://leekwars.com/settings" i find a button "Send confirmation e-mail" under "Change e-mail".
![image](https://user-images.githubusercontent.com/40393727/109703369-ab58d000-7b95-11eb-91e2-d7faa77bcdf0.png)
- Upon clicking on it i receive this e-mail: 
![image](https://user-images.githubusercontent.com/40393727/109703443-c62b4480-7b95-11eb-8c8b-385a7a6c995f.png)

I think that there is supposed to be a form to complete before sending the mail and it's actually missing but i don't know much about vue so i couldn't really dig in.

**Comment by 5pilow** [comment]
This should be fixed now, sorry!

**Comment by glamax13** [comment]
Perfect! Everything seems fine to me now!
Tanks a lot for this quick fix and good luck going forward :)
