### ISSUE TITLE
For, this, var... sont des noms valide d'attributs

### ISSUE THREAD

**Issue by Nyaleph** [leek-wars/leek-wars#601]
Il est possible, sans recevoir d'erreur, de creer une classe comme ceci:

```
class Test {
    var
    for
    this
    while
    
    constructor(a) {
        this.this = a
    }
}

debug(Test(10)) =>  Test {var: null, for: null, this: 10, while: null}
```

Ca parrait contre intuitif que cela fonctionne alors que les attributs sont colorés comme si ils étaient reconnus comme attribut...

**Comment by 5pilow** [comment]
C'est maintenant corrigé (LS3)
