### ISSUE TITLE
Talent graph is not updated in leek page

### ISSUE THREAD

**Issue by LucHenninot** [leek-wars/leek-wars#608]
On the leek page (when a leek is level >= 100) a graph is updated daily with the talent over the past 7 days.
The dates are correct but the graph is still the same and does not show the right values.

I tried to flush the browser cache and with a different browser.
It's the 2nd time I have this problem.
The last LW update (24/08/2021) fixed it.

Now it happens again.

**Comment by 5pilow** [comment]
I think it's fixed now, thanks :)

**Comment by LucHenninot** [comment]
Confirmé : les graphs sont à jour mais les stats des jours précédents sont
à 0.
Moindre mal ^^
Merci !!

Le sam. 2 oct. 2021 à 11:36, Pierre Lauprêtre ***@***.***> a
écrit :
