### ISSUE TITLE
[LeekScript] getSummons() compte les morts

### ISSUE THREAD

**Issue by JbIPS** [leek-wars/leek-wars#638]
Bonjour,

Je viens de me rendre compte d'un problème avec `getSummons()`. D'après la documentation : 
> Renvoie la liste des ids des invocations actuellement en vie de l'entité d'id entity.

Mais je viens de tracer la sortie lors d'un combat et 
![image](https://user-images.githubusercontent.com/2248473/145556218-b1573dfe-1adb-4dd5-a5c0-008f68a09e0f.png)
on voit que mon bulbe meurt mais ma ligne 
```
debug(count(getSummons()))
```
continue à renvoyer `1`.

Y a-t-il une subtilité que je n'aurais pas comprise ou s'agit-il d'un bug sur cette fonction ?

Merci à tous

**Comment by 5pilow** [comment]
Bonjour, c'est corrigé, la fonction getSummons() ne renvoie plus les invocations mortes.
