### ISSUE TITLE
[Editeur] Le détail de la puce s'affiche au-dessus de la puce

### ISSUE THREAD

**Issue by nytope** [leek-wars/leek-wars#641]
Dans l'éditeur, lorsqu'on veut modifier les puces ou les armes d'un poireau, le détail de la puce s'affiche au-dessus de la puce ce qui rend impossible de cliquer dessus pour l'ajouter au poireau.

![image](https://user-images.githubusercontent.com/34475564/147409945-94a78ecb-c265-4677-abdd-2c2a0ad6b827.png)

Au début j'ai voulu faire un bête transformX sur la classe "menuable__content__active" mais ça n'allait pas sur la page du poireau. En effet, sur la page du poireau il y a déjà un décalage pour qu'on puisse toujours cliquer sur la puce :

![image](https://user-images.githubusercontent.com/34475564/147409928-1c639f99-ff33-49c6-b42f-89f07ca3765c.png)

**Comment by 5pilow** [comment]
C'est OK maintenant
