### ISSUE TITLE
[Ostara] Interruption IA : Erreur d'exécution : Trop d'opérations exécutées pour ce tour

### ISSUE THREAD

**Issue by huguesW** [leek-wars/leek-wars#646]
Bonjour,

Je suis le joueur karamir sur leek wars,

depuis quelques temps j'ai un bug sur le nombre d'opérations de mon IA bulbe.
[Ostara] Interruption IA : Erreur d'exécution : Trop d'opérations exécutées pour ce tour.

Hors mon IA est des plus basique est demande peu d'opération par tour en moyenne 70k.

Peut-être ai-je dépasser le maximum?

Comme je n'avais pas d'autre moyen de contacter votre support je me permet de laisser une issue sur votre GITHUB.

Cordialment,
Hugues WARIN DUMONT

**Comment by nytope** [comment]
Bonjour karamir.

Le plus approprié est de faire un sujet sur le forum de leekwars, car il est plus probable que le problème viennent de ton IA plutôt que du jeu. Sauf si tu peux nous reproduire un code concis qui crée la même erreur d'exécution sans que ça soit justifié.

En ce qui concerne ton problème, voici plusieurs pistes :
- Les opérations pour les bulbes sont partagées avec les opérations pour les poireaux, donc si ton poireau consomme tout, alors il ne va rien rester pour le bulbe
- Une boucle infinie, tout simplement ?
- Le maximum d'opérations est en 20.000.000, donc loin de tes 70k par tour. Néanmoins, tu peux ajouter des `debug(getOperations());` dans ton code pour isoler la partie qui consomme plus de 20M.
