### ISSUE TITLE
Tooltips non affichés dans les rapports de combat

### ISSUE THREAD

**Issue by nytope** [leek-wars/leek-wars#650]
Dans les rapports de combats, dans le graphique d'évolution des points de vie, le tooltip du poireau ne s'affiche pas quand on survole sa ligne de vie. Il n'y a pas d'erreur dans la console au chargement du rapport de combat ni au survol.
Quand on rafraichit la page, les tooltips s'affichent bien.
Ce bug est présent depuis la dernière mise à jour.

Quand j'aurais le temps j'essaierai de le corriger. Sauf si tu travailles déjà dessus @5pilow.

**Comment by NyalephTheCat** [comment]
Ca a l'air d'etre un probleme de v-tooltip__content qui a son opacite set a 0 mais je n'arrive pas a trouver ou changer ca

**Comment by nytope** [comment]
Corrigé dans la v2.30
