### ISSUE TITLE
Mysterious removal of 2 TP on first turn

### ISSUE THREAD

**Issue by beaugunderson** [leek-wars/leek-wars#656]
Trying to figure out why these 2 TP are removed:

<img width="298" alt="image" src="https://user-images.githubusercontent.com/61791/174965299-8eaff4fc-a44d-447c-a14f-8dadd0eadd17.png">

Here's the [fight log](https://leekwars.com/report/37571669).

**Comment by 5pilow** [comment]
It is fixed :) It was just a bad copy paste for the SUMMON action in the report, thanks!
