### ISSUE TITLE
Comment puis-je avoir mon api key

### ISSUE THREAD

**Issue by TathanDev** [leek-wars/leek-wars#658]
J'essaye d'utiliser cette lib : https://www.npmjs.com/package/leek-api mais il me faut une apikey.

Merci^^

**Comment by 5pilow** [comment]
Salut, cette lib n'est pas liée à Leek Wars et est trop ancienne pour
fonctionner.

**Comment by TathanDev** [comment]
Ah ok 
Merci beaucoup

**Comment by TathanDev** [comment]
alors existe-t-il un moyen de get des infos ?
