### ISSUE TITLE
Delete des messages privés ? 

### ISSUE THREAD

**Issue by pseudonym-2669** [leek-wars/leek-wars#679]
On peut acutellement delete les messages dans le chat, mais on pourrait aussi delete ceux des messages privés ?
edit: on peut même delete les messages de teams, donc les DM ça serait bien.

**Comment by pseudonym-2669** [comment]
Est-ce volontaire d'avoir implémenter qu'on ne pouvait pas delete les messages privés ?
J'ai trouvé comment faire pour l'interface, mais l'API refuse (logiquement) donc il faudrait juste changer l'api :)

**Comment by 5pilow** [comment]
Je ne sais plus

**Comment by pseudonym-2669** [comment]
Ok, je fais la PR avec l'interface où on peut delete ?

**Comment by 5pilow** [comment]
Non je pense qu'on va rester comme ça, en effet j'avais prévu de ne pas pouvoir les supprimer

**Comment by pseudonym-2669** [comment]
Pourquoi ? Il y a une raison particulière ?

**Comment by 5pilow** [comment]
Je trouve ça bizarre c'est tout

**Comment by pseudonym-2669** [comment]
D'accord :) Donc je vais close l'issue
L'intérêt était de si par exemple il y avait quelqu'un qui envoyait un truc par mistake c'était bien de delete
