### ISSUE TITLE
Poireau neutre sans l'apparat

### ISSUE THREAD

**Issue by pseudonym-2669** [leek-wars/leek-wars#687]
Sans l'apparat on peut le mettre en neutre, et après on peut plus le remettre en "fâché" par contre :b

![Capture d’écran du 2022-12-14 14-39-54](https://user-images.githubusercontent.com/55923733/207610467-a9fc18e6-9f72-4fa7-b924-d9bd0c184b6b.png)

**Comment by 5pilow** [comment]
C'est normal
