### ISSUE TITLE
Affichage des armes oubliées dans la timeline

### ISSUE THREAD

**Issue by Astor-Bizard** [leek-wars/leek-wars#701]
Certaines armes oubliées, lorsqu'elles sont tenues en combat, s'affichent comme leur version normale dans la timeline :  

Armes qui semblent affectées :  
- WEAPON_ENHANCED_LIGHTNINGER (s'affiche comme WEAPON_LIGHTNINGER)
- WEAPON_UNSTABLE_DESTROYER (s'affiche comme WEAPON_DESTROYER)
- WEAPON_EXPLORER_RIFLE (s'affiche comme WEAPON_RIFLE)
- WEAPON_MYSTERIOUS_ELECTRISOR (s'affiche comme WEAPON_ELECTRISOR)

Armes qui semblent correctement affichées :  
- WEAPON_DARK_KATANA
- WEAPON_ILLICIT_GRENADE_LAUNCHER
- WEAPON_UNBRIDLED_GAZOR
- WEAPON_REVOKED_M_LASER

De plus, problème sans doute lié : attaquer avec ces armes oubliées indique dans la liste d'actions le nom de l'arme normale (uniquement en combat, le rapport de combat affiche la bonne arme)

Cf. le combat de test:  
39223433

**Comment by Astor-Bizard** [comment]
Après examen du code, ça semble être les armes qui dans src/component/player/game/weapon.ts héritent de leur version "normale". Les armes non affectées par le bug sont celles qui héritent d'une classe plus générique.

**Comment by Astor-Bizard** [comment]
Problème sans doute lié : attaquer avec ces armes oubliées indique dans la liste d'actions le nom de l'arme normale (uniquement en combat, le rapport de combat affiche la bonne arme)

**Comment by 5pilow** [comment]
ça sera corrigé dans une future màj merci beaucoup !
