### ISSUE TITLE
Forum: un topic ne se charge pas si l'auteur a supprimé son compte

### ISSUE THREAD

**Issue by sylvainclb** [leek-wars/leek-wars#702]
Salut,

Le topic suivant ne se charge plus https://leekwars.com/forum/category-7/topic-10336. 
J'ai deux hypothèses:

1. (Probable) La requête de chargement plante car il y a une dépendance sur l'éleveur auteur.
2. (Ouinnn) La suppression du compte de l'éleveur a supprimé ses posts.

Les data proviennent de l'api https://leekwars.com/api/forum/get-messages/10336/fr,en,es/1 qui donne une erreur http 401 (devrait être 404), avec pour réponse :
> {"error":"topic_not_exists"}

**Comment by CaptainTheDelta** [comment]
Ce n'est pas à l'hypothétique suppression du compte de l'auteur : [ce topic](https://leekwars.com/forum/category-5/topic-8973) est un contre-exemple

**Comment by 5pilow** [comment]
Le topic 10336 est supprimé en fait

**Comment by sylvainclb** [comment]
Ok merci. 
Je ferme cette issue qui n’en est plus une :)
