### ISSUE TITLE
Front en local inutilisable

### ISSUE THREAD

**Issue by Bug38** [leek-wars/leek-wars#741]
Hello !

L'installation et la compilation se passent sans encombre, puis quand j'arrive sur http://localhost:8080/ :
![image](https://github.com/user-attachments/assets/2e6ce0a8-8ae4-4f18-b874-4779624e7bcb)

Aucune erreur en console, ni dans les devtools...
J'ai le soucis sur Firefox et Edge, j'ai pas testé d'autres navigateurs (déjà que c'est pas souvent que j'ouvre Edge...).

Si quelqu'un a une piste, je suis preneur.
Si vous avez besoin d'infos, je suis dispo.

**Comment by 5pilow** [comment]
Salut :)

Tu peux juste cliquer sur la croix en haut à droite pour fermer l'erreur, qui n'est pas très importante.

**Comment by Bug38** [comment]
Ok c'est un non problème...
J'avais beau fermer la modal d'erreur, elle revenait tout le temps. Je sais pas pourquoi, mais en voulant réitérer pour en parler ici je n'ai plus de problème...
Merci :)
